// <auto-generated />
using System;
using GodlessAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GodlessAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612113255_potentialChanges")]
    partial class potentialChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GodlessAPI.Models.GodNumber", b =>
                {
                    b.Property<int>("GodNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GodNo");

                    b.ToTable("GodsNumbers");

                    b.HasData(
                        new
                        {
                            GodNo = 1,
                            CreationDate = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3599),
                            SpecialDetails = "SuperVision",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GodNo = 20,
                            CreationDate = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3603),
                            SpecialDetails = "BigDick",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GodNo = 333,
                            CreationDate = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3604),
                            SpecialDetails = "SuperYoung",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GodNo = 458,
                            CreationDate = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3606),
                            SpecialDetails = "Tripple Nipple",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GodNo = 566,
                            CreationDate = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3608),
                            SpecialDetails = "TechKing",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GodlessAPI.Models.Godless", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3436),
                            Name = "Product A"
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3488),
                            Name = "Thor"
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3490),
                            Name = "Odin A"
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3492),
                            Name = "Thanos A"
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 6, 12, 13, 32, 55, 467, DateTimeKind.Local).AddTicks(3494),
                            Name = "Julius A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
