// <auto-generated />
using System;
using GodlessAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GodlessAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GodlessAPI.Models.Godless", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2024, 5, 29, 13, 41, 58, 433, DateTimeKind.Local).AddTicks(3223),
                            Expiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Product A"
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2024, 5, 29, 13, 41, 58, 433, DateTimeKind.Local).AddTicks(3276),
                            Expiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thor"
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2024, 5, 29, 13, 41, 58, 433, DateTimeKind.Local).AddTicks(3287),
                            Expiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Odin A"
                        },
                        new
                        {
                            Id = 4,
                            Creation = new DateTime(2024, 5, 29, 13, 41, 58, 433, DateTimeKind.Local).AddTicks(3289),
                            Expiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thanos A"
                        },
                        new
                        {
                            Id = 5,
                            Creation = new DateTime(2024, 5, 29, 13, 41, 58, 433, DateTimeKind.Local).AddTicks(3290),
                            Expiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Julius A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
